# Generated by Django 2.2.8 on 2019-12-16 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountjournal',
            name='transaction',
        ),
    ]
